export const courses = [
  {
    courseName: "HTML & CSS",
    courseID: "CRWD1",
    coursePoster:
      "https://miro.medium.com/v2/resize:fit:1140/1*r0TkcCU3hKl7yuG5fFcZVA.png",
    courseContent: [
      "Introduction to HTML",
      "HTML Structure and Elements",
      "Introduction to CSS",
      "CSS Styling and Layout",
      "Responsive Web Design",
      "HTML and CSS Projects",
      "Building a Personal Website",
    ],
  },
  {
    courseName: "HTML, CSS & JS",
    courseID: "CRWD2",
    coursePoster: "https://petra-at.github.io/ZTM/images/html-css-js.jpg",
    courseContent: [
      "HTML and CSS Review",
      "Introduction to JavaScript",
      "JavaScript Functions and Events",
      "DOM Manipulation",
      "Front-End Development Projects",
      "Creating Interactive Websites",
    ],
  },
  {
    courseName: "JavaScript",
    courseID: "CRJS1",
    coursePoster:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/640px-JavaScript-logo.png",
    courseContent: [
      "JavaScript Basics",
      "JavaScript Functions and Objects",
      "Event Handling",
      "Asynchronous JavaScript",
      "DOM Manipulation",
      "JavaScript Projects",
      "Building Web Apps with Vanilla JS",
    ],
  },
  {
    courseName: "C Programming",
    courseID: "CRCP1",
    coursePoster: "https://cdn.worldvectorlogo.com/logos/c-1.svg",
    courseContent: [
      "Introduction to C Programming",
      "C Syntax and Variables",
      "Control Structures in C",
      "Functions and Pointers",
      "File Handling in C",
      "C Programming Projects",
    ],
  },
  {
    courseName: "C++ Programming",
    courseID: "CRCPP1",
    coursePoster:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/911px-ISO_C%2B%2B_Logo.svg.png",
    courseContent: [
      "Introduction to C++",
      "C++ Basics and Syntax",
      "Variables and Data Types",
      "Operators and Expressions",
      "Control Structures (if, else, switch, loops)",
      "Functions and Function Overloading",
      "Arrays and Strings",
      "Pointers and References",
      "Object-Oriented Programming (OOP) Concepts",
      "Classes and Objects",
      "File Input/Output",
      "Exception Handling",
      "Best Practices and Coding Style",
      "Projects and Mini-Assignments",
      "Final C++ Project",
    ],
  },
  {
    courseName: "Python",
    courseID: "CRPP1",
    coursePoster:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1869px-Python-logo-notext.svg.png",
    courseContent: [
      "Introduction to Python",
      "Python Syntax and Variables",
      "Control Structures in Python",
      "Functions and Modules",
      "Data Structures in Python (Lists, Tuples, Dictionaries)",
      "File Handling and Input/Output",
      "Object-Oriented Programming in Python (Classes and Objects)",
      "Exception Handling",
      "Unique Python Concepts (List Comprehensions, Lambda Functions, Generators)",
    ],
  },
  {
    courseName: "SQL",
    courseID: "CRSQL1",
    coursePoster:
      "https://techcommunity.microsoft.com/t5/image/serverpage/image-id/283585i32E35734ADB2BDF9/image-size/original?v=v2&px=-1",
    courseContent: [
      "Introduction to SQL",
      "SQL Data Types",
      "Database Design",
      "Querying Databases",
      "Data Manipulation",
      "Joins and Relationships",
      "Advanced SQL Concepts",
      "Practice Exercises",
      "Final Database Project",
    ],
  },
];
